name: Matthewn7-${project.artifactId}-${project.name}
version: ${project.version}
description: ${project.description}
authors: [JustMatt]
website: ${project.url}

main: ${project.groupId}.${project.artifactId}.${project.name}Plugin